// Generated by gencpp from file motion_control/getDiffAngle.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETDIFFANGLE_H
#define MOTION_CONTROL_MESSAGE_GETDIFFANGLE_H

#include <ros/service_traits.h>


#include <motion_control/getDiffAngleRequest.h>
#include <motion_control/getDiffAngleResponse.h>


namespace motion_control
{

struct getDiffAngle
{

typedef getDiffAngleRequest Request;
typedef getDiffAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getDiffAngle
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getDiffAngle > {
  static const char* value()
  {
    return "39a7032f716c41fca7c3cc6c27125bc3";
  }

  static const char* value(const ::motion_control::getDiffAngle&) { return value(); }
};

template<>
struct DataType< ::motion_control::getDiffAngle > {
  static const char* value()
  {
    return "motion_control/getDiffAngle";
  }

  static const char* value(const ::motion_control::getDiffAngle&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getDiffAngleRequest> should match 
// service_traits::MD5Sum< ::motion_control::getDiffAngle > 
template<>
struct MD5Sum< ::motion_control::getDiffAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getDiffAngle >::value();
  }
  static const char* value(const ::motion_control::getDiffAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getDiffAngleRequest> should match 
// service_traits::DataType< ::motion_control::getDiffAngle > 
template<>
struct DataType< ::motion_control::getDiffAngleRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getDiffAngle >::value();
  }
  static const char* value(const ::motion_control::getDiffAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getDiffAngleResponse> should match 
// service_traits::MD5Sum< ::motion_control::getDiffAngle > 
template<>
struct MD5Sum< ::motion_control::getDiffAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getDiffAngle >::value();
  }
  static const char* value(const ::motion_control::getDiffAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getDiffAngleResponse> should match 
// service_traits::DataType< ::motion_control::getDiffAngle > 
template<>
struct DataType< ::motion_control::getDiffAngleResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getDiffAngle >::value();
  }
  static const char* value(const ::motion_control::getDiffAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETDIFFANGLE_H
