// Generated by gencpp from file motion_control/getDiffAngleRequest.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETDIFFANGLEREQUEST_H
#define MOTION_CONTROL_MESSAGE_GETDIFFANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_control
{
template <class ContainerAllocator>
struct getDiffAngleRequest_
{
  typedef getDiffAngleRequest_<ContainerAllocator> Type;

  getDiffAngleRequest_()
    {
    }
  getDiffAngleRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::motion_control::getDiffAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_control::getDiffAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getDiffAngleRequest_

typedef ::motion_control::getDiffAngleRequest_<std::allocator<void> > getDiffAngleRequest;

typedef boost::shared_ptr< ::motion_control::getDiffAngleRequest > getDiffAngleRequestPtr;
typedef boost::shared_ptr< ::motion_control::getDiffAngleRequest const> getDiffAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_control::getDiffAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'motion_control': ['/home/eaibot/nju_ws/src/motion_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getDiffAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getDiffAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getDiffAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::motion_control::getDiffAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_control/getDiffAngleRequest";
  }

  static const char* value(const ::motion_control::getDiffAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::motion_control::getDiffAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getDiffAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_control::getDiffAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::motion_control::getDiffAngleRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETDIFFANGLEREQUEST_H
