// Generated by gencpp from file motion_control/getDiffAngleResponse.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETDIFFANGLERESPONSE_H
#define MOTION_CONTROL_MESSAGE_GETDIFFANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_control
{
template <class ContainerAllocator>
struct getDiffAngleResponse_
{
  typedef getDiffAngleResponse_<ContainerAllocator> Type;

  getDiffAngleResponse_()
    : diffAngle(0.0)  {
    }
  getDiffAngleResponse_(const ContainerAllocator& _alloc)
    : diffAngle(0.0)  {
  (void)_alloc;
    }



   typedef float _diffAngle_type;
  _diffAngle_type diffAngle;





  typedef boost::shared_ptr< ::motion_control::getDiffAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_control::getDiffAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getDiffAngleResponse_

typedef ::motion_control::getDiffAngleResponse_<std::allocator<void> > getDiffAngleResponse;

typedef boost::shared_ptr< ::motion_control::getDiffAngleResponse > getDiffAngleResponsePtr;
typedef boost::shared_ptr< ::motion_control::getDiffAngleResponse const> getDiffAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_control::getDiffAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'motion_control': ['/home/eaibot/nju_ws/src/motion_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getDiffAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getDiffAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getDiffAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39a7032f716c41fca7c3cc6c27125bc3";
  }

  static const char* value(const ::motion_control::getDiffAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39a7032f716c41fcULL;
  static const uint64_t static_value2 = 0xa7c3cc6c27125bc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_control/getDiffAngleResponse";
  }

  static const char* value(const ::motion_control::getDiffAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 diffAngle\n\
";
  }

  static const char* value(const ::motion_control::getDiffAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diffAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getDiffAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_control::getDiffAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_control::getDiffAngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "diffAngle: ";
    Printer<float>::stream(s, indent + "  ", v.diffAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETDIFFANGLERESPONSE_H
