// Generated by gencpp from file motion_control/getFrontDist.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETFRONTDIST_H
#define MOTION_CONTROL_MESSAGE_GETFRONTDIST_H

#include <ros/service_traits.h>


#include <motion_control/getFrontDistRequest.h>
#include <motion_control/getFrontDistResponse.h>


namespace motion_control
{

struct getFrontDist
{

typedef getFrontDistRequest Request;
typedef getFrontDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getFrontDist
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getFrontDist > {
  static const char* value()
  {
    return "1e75451363e2baac9b8bfb0e12a9fdd0";
  }

  static const char* value(const ::motion_control::getFrontDist&) { return value(); }
};

template<>
struct DataType< ::motion_control::getFrontDist > {
  static const char* value()
  {
    return "motion_control/getFrontDist";
  }

  static const char* value(const ::motion_control::getFrontDist&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getFrontDistRequest> should match 
// service_traits::MD5Sum< ::motion_control::getFrontDist > 
template<>
struct MD5Sum< ::motion_control::getFrontDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getFrontDist >::value();
  }
  static const char* value(const ::motion_control::getFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getFrontDistRequest> should match 
// service_traits::DataType< ::motion_control::getFrontDist > 
template<>
struct DataType< ::motion_control::getFrontDistRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getFrontDist >::value();
  }
  static const char* value(const ::motion_control::getFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getFrontDistResponse> should match 
// service_traits::MD5Sum< ::motion_control::getFrontDist > 
template<>
struct MD5Sum< ::motion_control::getFrontDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getFrontDist >::value();
  }
  static const char* value(const ::motion_control::getFrontDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getFrontDistResponse> should match 
// service_traits::DataType< ::motion_control::getFrontDist > 
template<>
struct DataType< ::motion_control::getFrontDistResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getFrontDist >::value();
  }
  static const char* value(const ::motion_control::getFrontDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETFRONTDIST_H
