// Generated by gencpp from file motion_control/getLeftDistResponse.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETLEFTDISTRESPONSE_H
#define MOTION_CONTROL_MESSAGE_GETLEFTDISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_control
{
template <class ContainerAllocator>
struct getLeftDistResponse_
{
  typedef getLeftDistResponse_<ContainerAllocator> Type;

  getLeftDistResponse_()
    : leftDist(0.0)  {
    }
  getLeftDistResponse_(const ContainerAllocator& _alloc)
    : leftDist(0.0)  {
  (void)_alloc;
    }



   typedef float _leftDist_type;
  _leftDist_type leftDist;





  typedef boost::shared_ptr< ::motion_control::getLeftDistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_control::getLeftDistResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getLeftDistResponse_

typedef ::motion_control::getLeftDistResponse_<std::allocator<void> > getLeftDistResponse;

typedef boost::shared_ptr< ::motion_control::getLeftDistResponse > getLeftDistResponsePtr;
typedef boost::shared_ptr< ::motion_control::getLeftDistResponse const> getLeftDistResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_control::getLeftDistResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_control::getLeftDistResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'motion_control': ['/home/eaibot/nju_ws/src/motion_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getLeftDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getLeftDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getLeftDistResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e0d27729a997215618b53389df19443";
  }

  static const char* value(const ::motion_control::getLeftDistResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e0d27729a997215ULL;
  static const uint64_t static_value2 = 0x618b53389df19443ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_control/getLeftDistResponse";
  }

  static const char* value(const ::motion_control::getLeftDistResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftDist\n\
";
  }

  static const char* value(const ::motion_control::getLeftDistResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftDist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getLeftDistResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_control::getLeftDistResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_control::getLeftDistResponse_<ContainerAllocator>& v)
  {
    s << indent << "leftDist: ";
    Printer<float>::stream(s, indent + "  ", v.leftDist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETLEFTDISTRESPONSE_H
