// Generated by gencpp from file motion_control/getLeftFrontDist.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETLEFTFRONTDIST_H
#define MOTION_CONTROL_MESSAGE_GETLEFTFRONTDIST_H

#include <ros/service_traits.h>


#include <motion_control/getLeftFrontDistRequest.h>
#include <motion_control/getLeftFrontDistResponse.h>


namespace motion_control
{

struct getLeftFrontDist
{

typedef getLeftFrontDistRequest Request;
typedef getLeftFrontDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLeftFrontDist
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getLeftFrontDist > {
  static const char* value()
  {
    return "4c23ace1d1a78b192ca63b2f98acf0d3";
  }

  static const char* value(const ::motion_control::getLeftFrontDist&) { return value(); }
};

template<>
struct DataType< ::motion_control::getLeftFrontDist > {
  static const char* value()
  {
    return "motion_control/getLeftFrontDist";
  }

  static const char* value(const ::motion_control::getLeftFrontDist&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getLeftFrontDistRequest> should match 
// service_traits::MD5Sum< ::motion_control::getLeftFrontDist > 
template<>
struct MD5Sum< ::motion_control::getLeftFrontDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getLeftFrontDist >::value();
  }
  static const char* value(const ::motion_control::getLeftFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getLeftFrontDistRequest> should match 
// service_traits::DataType< ::motion_control::getLeftFrontDist > 
template<>
struct DataType< ::motion_control::getLeftFrontDistRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getLeftFrontDist >::value();
  }
  static const char* value(const ::motion_control::getLeftFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getLeftFrontDistResponse> should match 
// service_traits::MD5Sum< ::motion_control::getLeftFrontDist > 
template<>
struct MD5Sum< ::motion_control::getLeftFrontDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getLeftFrontDist >::value();
  }
  static const char* value(const ::motion_control::getLeftFrontDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getLeftFrontDistResponse> should match 
// service_traits::DataType< ::motion_control::getLeftFrontDist > 
template<>
struct DataType< ::motion_control::getLeftFrontDistResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getLeftFrontDist >::value();
  }
  static const char* value(const ::motion_control::getLeftFrontDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETLEFTFRONTDIST_H
