// Generated by gencpp from file motion_control/getLeftDist.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETLEFTDIST_H
#define MOTION_CONTROL_MESSAGE_GETLEFTDIST_H

#include <ros/service_traits.h>


#include <motion_control/getLeftDistRequest.h>
#include <motion_control/getLeftDistResponse.h>


namespace motion_control
{

struct getLeftDist
{

typedef getLeftDistRequest Request;
typedef getLeftDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLeftDist
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getLeftDist > {
  static const char* value()
  {
    return "4e0d27729a997215618b53389df19443";
  }

  static const char* value(const ::motion_control::getLeftDist&) { return value(); }
};

template<>
struct DataType< ::motion_control::getLeftDist > {
  static const char* value()
  {
    return "motion_control/getLeftDist";
  }

  static const char* value(const ::motion_control::getLeftDist&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getLeftDistRequest> should match 
// service_traits::MD5Sum< ::motion_control::getLeftDist > 
template<>
struct MD5Sum< ::motion_control::getLeftDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getLeftDist >::value();
  }
  static const char* value(const ::motion_control::getLeftDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getLeftDistRequest> should match 
// service_traits::DataType< ::motion_control::getLeftDist > 
template<>
struct DataType< ::motion_control::getLeftDistRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getLeftDist >::value();
  }
  static const char* value(const ::motion_control::getLeftDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getLeftDistResponse> should match 
// service_traits::MD5Sum< ::motion_control::getLeftDist > 
template<>
struct MD5Sum< ::motion_control::getLeftDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getLeftDist >::value();
  }
  static const char* value(const ::motion_control::getLeftDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getLeftDistResponse> should match 
// service_traits::DataType< ::motion_control::getLeftDist > 
template<>
struct DataType< ::motion_control::getLeftDistResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getLeftDist >::value();
  }
  static const char* value(const ::motion_control::getLeftDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETLEFTDIST_H
