// Generated by gencpp from file motion_control/getRightFrontDistResponse.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDISTRESPONSE_H
#define MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_control
{
template <class ContainerAllocator>
struct getRightFrontDistResponse_
{
  typedef getRightFrontDistResponse_<ContainerAllocator> Type;

  getRightFrontDistResponse_()
    : rightFrontDist(0.0)  {
    }
  getRightFrontDistResponse_(const ContainerAllocator& _alloc)
    : rightFrontDist(0.0)  {
  (void)_alloc;
    }



   typedef float _rightFrontDist_type;
  _rightFrontDist_type rightFrontDist;





  typedef boost::shared_ptr< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getRightFrontDistResponse_

typedef ::motion_control::getRightFrontDistResponse_<std::allocator<void> > getRightFrontDistResponse;

typedef boost::shared_ptr< ::motion_control::getRightFrontDistResponse > getRightFrontDistResponsePtr;
typedef boost::shared_ptr< ::motion_control::getRightFrontDistResponse const> getRightFrontDistResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_control::getRightFrontDistResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'motion_control': ['/home/eaibot/nju_ws/src/motion_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b33671b8766d8b0db5bcef50e936b90c";
  }

  static const char* value(const ::motion_control::getRightFrontDistResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb33671b8766d8b0dULL;
  static const uint64_t static_value2 = 0xb5bcef50e936b90cULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_control/getRightFrontDistResponse";
  }

  static const char* value(const ::motion_control::getRightFrontDistResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rightFrontDist\n\
";
  }

  static const char* value(const ::motion_control::getRightFrontDistResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rightFrontDist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getRightFrontDistResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_control::getRightFrontDistResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_control::getRightFrontDistResponse_<ContainerAllocator>& v)
  {
    s << indent << "rightFrontDist: ";
    Printer<float>::stream(s, indent + "  ", v.rightFrontDist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDISTRESPONSE_H
