// Generated by gencpp from file motion_control/getRightFrontDist.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDIST_H
#define MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDIST_H

#include <ros/service_traits.h>


#include <motion_control/getRightFrontDistRequest.h>
#include <motion_control/getRightFrontDistResponse.h>


namespace motion_control
{

struct getRightFrontDist
{

typedef getRightFrontDistRequest Request;
typedef getRightFrontDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getRightFrontDist
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getRightFrontDist > {
  static const char* value()
  {
    return "b33671b8766d8b0db5bcef50e936b90c";
  }

  static const char* value(const ::motion_control::getRightFrontDist&) { return value(); }
};

template<>
struct DataType< ::motion_control::getRightFrontDist > {
  static const char* value()
  {
    return "motion_control/getRightFrontDist";
  }

  static const char* value(const ::motion_control::getRightFrontDist&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getRightFrontDistRequest> should match 
// service_traits::MD5Sum< ::motion_control::getRightFrontDist > 
template<>
struct MD5Sum< ::motion_control::getRightFrontDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getRightFrontDist >::value();
  }
  static const char* value(const ::motion_control::getRightFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getRightFrontDistRequest> should match 
// service_traits::DataType< ::motion_control::getRightFrontDist > 
template<>
struct DataType< ::motion_control::getRightFrontDistRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getRightFrontDist >::value();
  }
  static const char* value(const ::motion_control::getRightFrontDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getRightFrontDistResponse> should match 
// service_traits::MD5Sum< ::motion_control::getRightFrontDist > 
template<>
struct MD5Sum< ::motion_control::getRightFrontDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getRightFrontDist >::value();
  }
  static const char* value(const ::motion_control::getRightFrontDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getRightFrontDistResponse> should match 
// service_traits::DataType< ::motion_control::getRightFrontDist > 
template<>
struct DataType< ::motion_control::getRightFrontDistResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getRightFrontDist >::value();
  }
  static const char* value(const ::motion_control::getRightFrontDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETRIGHTFRONTDIST_H
