// Generated by gencpp from file motion_control/getRightDist.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MESSAGE_GETRIGHTDIST_H
#define MOTION_CONTROL_MESSAGE_GETRIGHTDIST_H

#include <ros/service_traits.h>


#include <motion_control/getRightDistRequest.h>
#include <motion_control/getRightDistResponse.h>


namespace motion_control
{

struct getRightDist
{

typedef getRightDistRequest Request;
typedef getRightDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getRightDist
} // namespace motion_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_control::getRightDist > {
  static const char* value()
  {
    return "46d3dd3b27754b2db4e99d35f4cb12c3";
  }

  static const char* value(const ::motion_control::getRightDist&) { return value(); }
};

template<>
struct DataType< ::motion_control::getRightDist > {
  static const char* value()
  {
    return "motion_control/getRightDist";
  }

  static const char* value(const ::motion_control::getRightDist&) { return value(); }
};


// service_traits::MD5Sum< ::motion_control::getRightDistRequest> should match 
// service_traits::MD5Sum< ::motion_control::getRightDist > 
template<>
struct MD5Sum< ::motion_control::getRightDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getRightDist >::value();
  }
  static const char* value(const ::motion_control::getRightDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getRightDistRequest> should match 
// service_traits::DataType< ::motion_control::getRightDist > 
template<>
struct DataType< ::motion_control::getRightDistRequest>
{
  static const char* value()
  {
    return DataType< ::motion_control::getRightDist >::value();
  }
  static const char* value(const ::motion_control::getRightDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_control::getRightDistResponse> should match 
// service_traits::MD5Sum< ::motion_control::getRightDist > 
template<>
struct MD5Sum< ::motion_control::getRightDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_control::getRightDist >::value();
  }
  static const char* value(const ::motion_control::getRightDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_control::getRightDistResponse> should match 
// service_traits::DataType< ::motion_control::getRightDist > 
template<>
struct DataType< ::motion_control::getRightDistResponse>
{
  static const char* value()
  {
    return DataType< ::motion_control::getRightDist >::value();
  }
  static const char* value(const ::motion_control::getRightDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CONTROL_MESSAGE_GETRIGHTDIST_H
