(cl:defpackage camera-srv
  (:use )
  (:export
   "PHOTOSERVICE"
   "<PHOTOSERVICE-REQUEST>"
   "PHOTOSERVICE-REQUEST"
   "<PHOTOSERVICE-RESPONSE>"
   "PHOTOSERVICE-RESPONSE"
   "PHOTOBOXSERVICE"
   "<PHOTOBOXSERVICE-REQUEST>"
   "PHOTOBOXSERVICE-REQUEST"
   "<PHOTOBOXSERVICE-RESPONSE>"
   "PHOTOBOXSERVICE-RESPONSE"
   "PHOTOSHELFSERVICE"
   "<PHOTOSHELFSERVICE-REQUEST>"
   "PHOTOSHELFSERVICE-REQUEST"
   "<PHOTOSHELFSERVICE-RESPONSE>"
   "PHOTOSHELFSERVICE-RESPONSE"
  ))

