// Generated by gencpp from file camera/PhotoboxService.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOBOXSERVICE_H
#define CAMERA_MESSAGE_PHOTOBOXSERVICE_H

#include <ros/service_traits.h>


#include <camera/PhotoboxServiceRequest.h>
#include <camera/PhotoboxServiceResponse.h>


namespace camera
{

struct PhotoboxService
{

typedef PhotoboxServiceRequest Request;
typedef PhotoboxServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PhotoboxService
} // namespace camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera::PhotoboxService > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::camera::PhotoboxService&) { return value(); }
};

template<>
struct DataType< ::camera::PhotoboxService > {
  static const char* value()
  {
    return "camera/PhotoboxService";
  }

  static const char* value(const ::camera::PhotoboxService&) { return value(); }
};


// service_traits::MD5Sum< ::camera::PhotoboxServiceRequest> should match 
// service_traits::MD5Sum< ::camera::PhotoboxService > 
template<>
struct MD5Sum< ::camera::PhotoboxServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoboxService >::value();
  }
  static const char* value(const ::camera::PhotoboxServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoboxServiceRequest> should match 
// service_traits::DataType< ::camera::PhotoboxService > 
template<>
struct DataType< ::camera::PhotoboxServiceRequest>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoboxService >::value();
  }
  static const char* value(const ::camera::PhotoboxServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera::PhotoboxServiceResponse> should match 
// service_traits::MD5Sum< ::camera::PhotoboxService > 
template<>
struct MD5Sum< ::camera::PhotoboxServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoboxService >::value();
  }
  static const char* value(const ::camera::PhotoboxServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoboxServiceResponse> should match 
// service_traits::DataType< ::camera::PhotoboxService > 
template<>
struct DataType< ::camera::PhotoboxServiceResponse>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoboxService >::value();
  }
  static const char* value(const ::camera::PhotoboxServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOBOXSERVICE_H
