// Generated by gencpp from file camera/PhotoshelfService.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSHELFSERVICE_H
#define CAMERA_MESSAGE_PHOTOSHELFSERVICE_H

#include <ros/service_traits.h>


#include <camera/PhotoshelfServiceRequest.h>
#include <camera/PhotoshelfServiceResponse.h>


namespace camera
{

struct PhotoshelfService
{

typedef PhotoshelfServiceRequest Request;
typedef PhotoshelfServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PhotoshelfService
} // namespace camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera::PhotoshelfService > {
  static const char* value()
  {
    return "b956cbec76bf70325b60df673b2d7722";
  }

  static const char* value(const ::camera::PhotoshelfService&) { return value(); }
};

template<>
struct DataType< ::camera::PhotoshelfService > {
  static const char* value()
  {
    return "camera/PhotoshelfService";
  }

  static const char* value(const ::camera::PhotoshelfService&) { return value(); }
};


// service_traits::MD5Sum< ::camera::PhotoshelfServiceRequest> should match 
// service_traits::MD5Sum< ::camera::PhotoshelfService > 
template<>
struct MD5Sum< ::camera::PhotoshelfServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoshelfService >::value();
  }
  static const char* value(const ::camera::PhotoshelfServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoshelfServiceRequest> should match 
// service_traits::DataType< ::camera::PhotoshelfService > 
template<>
struct DataType< ::camera::PhotoshelfServiceRequest>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoshelfService >::value();
  }
  static const char* value(const ::camera::PhotoshelfServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera::PhotoshelfServiceResponse> should match 
// service_traits::MD5Sum< ::camera::PhotoshelfService > 
template<>
struct MD5Sum< ::camera::PhotoshelfServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoshelfService >::value();
  }
  static const char* value(const ::camera::PhotoshelfServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoshelfServiceResponse> should match 
// service_traits::DataType< ::camera::PhotoshelfService > 
template<>
struct DataType< ::camera::PhotoshelfServiceResponse>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoshelfService >::value();
  }
  static const char* value(const ::camera::PhotoshelfServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSHELFSERVICE_H
