// Generated by gencpp from file camera/PhotoServiceResponse.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H
#define CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct PhotoServiceResponse_
{
  typedef PhotoServiceResponse_<ContainerAllocator> Type;

  PhotoServiceResponse_()
    : error_x(0.0)
    , error_y(0.0)  {
    }
  PhotoServiceResponse_(const ContainerAllocator& _alloc)
    : error_x(0.0)
    , error_y(0.0)  {
  (void)_alloc;
    }



   typedef float _error_x_type;
  _error_x_type error_x;

   typedef float _error_y_type;
  _error_y_type error_y;





  typedef boost::shared_ptr< ::camera::PhotoServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::PhotoServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PhotoServiceResponse_

typedef ::camera::PhotoServiceResponse_<std::allocator<void> > PhotoServiceResponse;

typedef boost::shared_ptr< ::camera::PhotoServiceResponse > PhotoServiceResponsePtr;
typedef boost::shared_ptr< ::camera::PhotoServiceResponse const> PhotoServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::PhotoServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::PhotoServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'camera': ['/home/eaibot/nju_ws/src/camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49012d3a75867c44d7c8a631f08af3cd";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49012d3a75867c44ULL;
  static const uint64_t static_value2 = 0xd7c8a631f08af3cdULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/PhotoServiceResponse";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 error_x\n\
float32 error_y\n\
";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_x);
      stream.next(m.error_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhotoServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::PhotoServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "error_x: ";
    Printer<float>::stream(s, indent + "  ", v.error_x);
    s << indent << "error_y: ";
    Printer<float>::stream(s, indent + "  ", v.error_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H
