// Generated by gencpp from file camera/PhotoboxSICHUANService.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOBOXSICHUANSERVICE_H
#define CAMERA_MESSAGE_PHOTOBOXSICHUANSERVICE_H

#include <ros/service_traits.h>


#include <camera/PhotoboxSICHUANServiceRequest.h>
#include <camera/PhotoboxSICHUANServiceResponse.h>


namespace camera
{

struct PhotoboxSICHUANService
{

typedef PhotoboxSICHUANServiceRequest Request;
typedef PhotoboxSICHUANServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PhotoboxSICHUANService
} // namespace camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera::PhotoboxSICHUANService > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::camera::PhotoboxSICHUANService&) { return value(); }
};

template<>
struct DataType< ::camera::PhotoboxSICHUANService > {
  static const char* value()
  {
    return "camera/PhotoboxSICHUANService";
  }

  static const char* value(const ::camera::PhotoboxSICHUANService&) { return value(); }
};


// service_traits::MD5Sum< ::camera::PhotoboxSICHUANServiceRequest> should match 
// service_traits::MD5Sum< ::camera::PhotoboxSICHUANService > 
template<>
struct MD5Sum< ::camera::PhotoboxSICHUANServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoboxSICHUANService >::value();
  }
  static const char* value(const ::camera::PhotoboxSICHUANServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoboxSICHUANServiceRequest> should match 
// service_traits::DataType< ::camera::PhotoboxSICHUANService > 
template<>
struct DataType< ::camera::PhotoboxSICHUANServiceRequest>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoboxSICHUANService >::value();
  }
  static const char* value(const ::camera::PhotoboxSICHUANServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera::PhotoboxSICHUANServiceResponse> should match 
// service_traits::MD5Sum< ::camera::PhotoboxSICHUANService > 
template<>
struct MD5Sum< ::camera::PhotoboxSICHUANServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera::PhotoboxSICHUANService >::value();
  }
  static const char* value(const ::camera::PhotoboxSICHUANServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::PhotoboxSICHUANServiceResponse> should match 
// service_traits::DataType< ::camera::PhotoboxSICHUANService > 
template<>
struct DataType< ::camera::PhotoboxSICHUANServiceResponse>
{
  static const char* value()
  {
    return DataType< ::camera::PhotoboxSICHUANService >::value();
  }
  static const char* value(const ::camera::PhotoboxSICHUANServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOBOXSICHUANSERVICE_H
