// Generated by gencpp from file camera/PhotoshelfServiceRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSHELFSERVICEREQUEST_H
#define CAMERA_MESSAGE_PHOTOSHELFSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct PhotoshelfServiceRequest_
{
  typedef PhotoshelfServiceRequest_<ContainerAllocator> Type;

  PhotoshelfServiceRequest_()
    : type(0)  {
    }
  PhotoshelfServiceRequest_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PhotoshelfServiceRequest_

typedef ::camera::PhotoshelfServiceRequest_<std::allocator<void> > PhotoshelfServiceRequest;

typedef boost::shared_ptr< ::camera::PhotoshelfServiceRequest > PhotoshelfServiceRequestPtr;
typedef boost::shared_ptr< ::camera::PhotoshelfServiceRequest const> PhotoshelfServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::PhotoshelfServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'camera': ['/home/eaibot/nju_ws/src/camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bda37decd5e3814bcc042f341d2e60a1";
  }

  static const char* value(const ::camera::PhotoshelfServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbda37decd5e3814bULL;
  static const uint64_t static_value2 = 0xcc042f341d2e60a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/PhotoshelfServiceRequest";
  }

  static const char* value(const ::camera::PhotoshelfServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n\
";
  }

  static const char* value(const ::camera::PhotoshelfServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhotoshelfServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::PhotoshelfServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::PhotoshelfServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSHELFSERVICEREQUEST_H
