// Generated by gencpp from file dobot/GraspService.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GRASPSERVICE_H
#define DOBOT_MESSAGE_GRASPSERVICE_H

#include <ros/service_traits.h>


#include <dobot/GraspServiceRequest.h>
#include <dobot/GraspServiceResponse.h>


namespace dobot
{

struct GraspService
{

typedef GraspServiceRequest Request;
typedef GraspServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspService
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GraspService > {
  static const char* value()
  {
    return "1e7660736e31416d5bfaa2f3f2cf2e32";
  }

  static const char* value(const ::dobot::GraspService&) { return value(); }
};

template<>
struct DataType< ::dobot::GraspService > {
  static const char* value()
  {
    return "dobot/GraspService";
  }

  static const char* value(const ::dobot::GraspService&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GraspServiceRequest> should match 
// service_traits::MD5Sum< ::dobot::GraspService > 
template<>
struct MD5Sum< ::dobot::GraspServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GraspService >::value();
  }
  static const char* value(const ::dobot::GraspServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GraspServiceRequest> should match 
// service_traits::DataType< ::dobot::GraspService > 
template<>
struct DataType< ::dobot::GraspServiceRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GraspService >::value();
  }
  static const char* value(const ::dobot::GraspServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GraspServiceResponse> should match 
// service_traits::MD5Sum< ::dobot::GraspService > 
template<>
struct MD5Sum< ::dobot::GraspServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GraspService >::value();
  }
  static const char* value(const ::dobot::GraspServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GraspServiceResponse> should match 
// service_traits::DataType< ::dobot::GraspService > 
template<>
struct DataType< ::dobot::GraspServiceResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GraspService >::value();
  }
  static const char* value(const ::dobot::GraspServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GRASPSERVICE_H
