// Generated by gencpp from file dobot/GraspServiceRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GRASPSERVICEREQUEST_H
#define DOBOT_MESSAGE_GRASPSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GraspServiceRequest_
{
  typedef GraspServiceRequest_<ContainerAllocator> Type;

  GraspServiceRequest_()
    : shelf_z(false)
    , pos_z(false)
    , error_x(0.0)
    , error_y(0.0)  {
    }
  GraspServiceRequest_(const ContainerAllocator& _alloc)
    : shelf_z(false)
    , pos_z(false)
    , error_x(0.0)
    , error_y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _shelf_z_type;
  _shelf_z_type shelf_z;

   typedef uint8_t _pos_z_type;
  _pos_z_type pos_z;

   typedef float _error_x_type;
  _error_x_type error_x;

   typedef float _error_y_type;
  _error_y_type error_y;





  typedef boost::shared_ptr< ::dobot::GraspServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GraspServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspServiceRequest_

typedef ::dobot::GraspServiceRequest_<std::allocator<void> > GraspServiceRequest;

typedef boost::shared_ptr< ::dobot::GraspServiceRequest > GraspServiceRequestPtr;
typedef boost::shared_ptr< ::dobot::GraspServiceRequest const> GraspServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GraspServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GraspServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/eaibot/nju_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GraspServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GraspServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GraspServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GraspServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GraspServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GraspServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GraspServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba764222789330d239513964a79bae26";
  }

  static const char* value(const ::dobot::GraspServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba764222789330d2ULL;
  static const uint64_t static_value2 = 0x39513964a79bae26ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GraspServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GraspServiceRequest";
  }

  static const char* value(const ::dobot::GraspServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GraspServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool shelf_z\n\
bool pos_z\n\
float32 error_x\n\
float32 error_y\n\
";
  }

  static const char* value(const ::dobot::GraspServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GraspServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shelf_z);
      stream.next(m.pos_z);
      stream.next(m.error_x);
      stream.next(m.error_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GraspServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GraspServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "shelf_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shelf_z);
    s << indent << "pos_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_z);
    s << indent << "error_x: ";
    Printer<float>::stream(s, indent + "  ", v.error_x);
    s << indent << "error_y: ";
    Printer<float>::stream(s, indent + "  ", v.error_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GRASPSERVICEREQUEST_H
