// Generated by gencpp from file dobot/ThrowServiceRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_THROWSERVICEREQUEST_H
#define DOBOT_MESSAGE_THROWSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct ThrowServiceRequest_
{
  typedef ThrowServiceRequest_<ContainerAllocator> Type;

  ThrowServiceRequest_()
    : pos_z(false)
    , mailbox_pos(false)  {
    }
  ThrowServiceRequest_(const ContainerAllocator& _alloc)
    : pos_z(false)
    , mailbox_pos(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pos_z_type;
  _pos_z_type pos_z;

   typedef uint8_t _mailbox_pos_type;
  _mailbox_pos_type mailbox_pos;





  typedef boost::shared_ptr< ::dobot::ThrowServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::ThrowServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ThrowServiceRequest_

typedef ::dobot::ThrowServiceRequest_<std::allocator<void> > ThrowServiceRequest;

typedef boost::shared_ptr< ::dobot::ThrowServiceRequest > ThrowServiceRequestPtr;
typedef boost::shared_ptr< ::dobot::ThrowServiceRequest const> ThrowServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::ThrowServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::ThrowServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/eaibot/nju_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::ThrowServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::ThrowServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::ThrowServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb345315c2037379bea93776fcff6049";
  }

  static const char* value(const ::dobot::ThrowServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb345315c2037379ULL;
  static const uint64_t static_value2 = 0xbea93776fcff6049ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/ThrowServiceRequest";
  }

  static const char* value(const ::dobot::ThrowServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool pos_z\n\
bool mailbox_pos\n\
";
  }

  static const char* value(const ::dobot::ThrowServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_z);
      stream.next(m.mailbox_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrowServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::ThrowServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::ThrowServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_z);
    s << indent << "mailbox_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mailbox_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_THROWSERVICEREQUEST_H
